# Generated by Django 3.2.16 on 2022-12-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_code', models.CharField(max_length=20, unique=True)),
                ('bc_name', models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cl', models.CharField(max_length=200, unique=True)),
                ('num_peticiones', models.IntegerField(default=0)),
                ('num_allowed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_peticion', models.DateField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdivs.banco')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdivs.client')),
            ],
        ),
    ]
