# Generated by Django 3.2.10 on 2022-12-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdivs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('compra', models.IntegerField(default=0)),
                ('venta', models.IntegerField(default=0)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdivs.banco')),
            ],
        ),
    ]
