# Generated by Django 3.2.10 on 2022-12-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdivs', '0002_divisas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisas',
            name='compra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='divisas',
            name='venta',
            field=models.FloatField(),
        ),
    ]
